language: go

go:
- 1.10.x

env:
  global:
    - OPERATOR_NAME=unifiedpush-operator

stages:
- test
- compile

jobs:
  include:
  - stage: test
    script:
    - cd ${HOME}/gopath/src/github.com/aerogear/${OPERATOR_NAME}
    - make setup/travis test/unit
  - stage: compile
    script:
    - make setup/travis
    - operator-sdk build quay.io/aerogear/${OPERATOR_NAME}:$(git rev-parse --short ${TRAVIS_COMMIT})
