:toc:
:toc-placement!:

// gEmoji for admonitions, see
// https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74#admonitions
ifdef::env-github[]
:status:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:table-caption!:
:warning-caption: :warning:
endif::[]

// Links (alphabetical order)
:apache_license: http://www.apache.org/licenses/LICENSE-2.0[Apache License, Version 2.0]
:application_monitoring_operator: https://github.com/integr8ly/application-monitoring-operator[application-monitoring-operator]
:code_of_conduct: link:CODE_OF_CONDUCT.md[Contributor Code of Conduct]
:export_policy: https://aerogear.org/legal/export.html[AeroGear Export Policy]
:aerogear_freenode: irc://irc.freenode.net/aerogear[#aerogear on FreeNode IRC]
:aerogear_jira: https://issues.jboss.org/projects/AEROGEAR/issues[AeroGear on JBoss Jira]
:aerogear_matrix: https://matrix.to/#/!IipcvbGVqkiTUQauSC:matrix.org[#aerogear:matrix.org on Matrix]
:mailing_list: https://groups.google.com/forum/#!forum/aerogear[Google Groups Mailing List]
:minishift: https://github.com/minishift/minishift[Minishift]
:rh_product_security: https://access.redhat.com/security/team/contact[Red Hat Product Security team]

= UnifiedPush Operator

ifdef::status[]
.*Project health*
image:https://circleci.com/gh/aerogear/unifiedpush-operator.svg?style=svg[Build Status (CircleCI), link=https://circleci.com/gh/aerogear/unifiedpush-operator]
image:https://img.shields.io/:license-Apache2-blue.svg[License (License), link=http://www.apache.org/licenses/LICENSE-2.0]
image:https://coveralls.io/repos/github/aerogear/unifiedpush-operator/badge.svg?branch=master[Coverage Status (Coveralls), link=https://coveralls.io/github/aerogear/unifiedpush-operator?branch=master]
image:https://goreportcard.com/badge/github.com/aerogear/unifiedpush-operator[Go Report Card (Go Report Card), link=https://goreportcard.com/report/github.com/aerogear/unifiedpush-operator]
endif::[]

toc::[]

== Overview

The UnifiedPush Operator for Kubernetes provides an easy way to install and manage an https://aerogear.org/docs/unifiedpush/[AeroGear UnifiedPush] Server on OpenShift.

== Prerequisites

|===
|https://golang.org/doc/install[Install Go]
|https://github.com/golang/go/wiki/SettingGOPATH[Ensure the $GOPATH environment variable is set]
|https://golang.github.io/dep/docs/installation.html[Install the dep package manager]
|https://github.com/operator-framework/operator-sdk#quick-start[Install Operator-SDK]
|https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl[Install kubectl]
|===

== Getting Started

=== Cloning the repository

By the following commands you will create a local directory and clone this project.

[source,shell]
----
$ git clone git@github.com:aerogear/unifiedpush-operator.git $GOPATH/src/github.com/aerogear/unifiedpush-operator
----

=== Minishift installation and setup

https://docs.okd.io/latest/minishift/getting-started/installing.html[Install Minishift] then install Operators on it by running the following commands.

[source,shell]
----
# create a new profile to test the operator
$ minishift profile set unifiedpush-operator

# enable the admin-user add-on
$ minishift addon enable admin-user

# add insecure registry to download the images from docker
$ minishift config set insecure-registry 172.30.0.0/16

# start the instance
$ minishift start
----

NOTE: The above steps are not required in OCP > 4 since the OLM and Operators came installed by default.

=== Installing

Use the following command to install the UnifiedPush Operator and Service in your OpenShift cluster as follows:

[source,shell]
----
$ make install
----

NOTE: To install you need be logged in as a user with cluster privileges like the `system:admin` user. E.g. By using: `oc login -u system:admin`.

=== Creating PushApplication

* Create a link:./deploy/crds/examples/push_v1alpha1_pushapplication_cr.yaml[PushApplication CR] as this example.
+
The app name and description need to be specified into the link:./deploy/crds/examples/push_v1alpha1_pushapplication_cr.yaml[PushApplication CR] as follows.
+
[source,yaml]
----
apiVersion: push.aerogear.org/v1alpha1
kind: PushApplication
metadata:
  name: example-pushapplication
spec:
  description: 'An example push application to demonstrate the
    unifiedpush-operator'
----
+
* Run the following command to create the PushApplication into the Service
+
[source,shell]
----
$ make example-pushapplication/apply
----
+
NOTE: You can delete it by running `make example-pushapplication/delete`

=== Creating an AndroidVariant for your App

After creating the PushApplication above, you should be able to get
the `pushApplicationId` from the status, this will be needed to be
able to create Variants:
+
[source,shell]
----
kubectl get pushApplication example-pushapplication -n unifiedpush -o jsonpath='{.status.pushApplicationId}'
----
+
Here are all of the configurable fields in an AndroidVariant:
+
|===
|Field Name |Description

|pushApplicationId
|ID of the PushApplication that this variant corresponds to

|description
|Human friendly description for the variant

|senderId
|The "Google Project Number from the API Console

|serverKey
|The key from the Firebase Console of a project which has been enabled for FCM
|===

* Apply an AndroidVariantCR based on the example a link:./deploy/crds/examples/push_v1alpha1_androidvariant_cr.yaml[AndroidVariant CR]  as follows:
+
[source,shell]
----
kubectl apply -f ./deploy/crds/examples/push_v1alpha1_androidvariant_cr.yaml
----

=== Creating an IOSVariant for your App

After creating the PushApplication above, you should be able to get the `pushApplicationId` from the status, this will be needed to be able to create Variants:

[source,shell]
----
kubectl get PushApplication example-pushapplication -n unifiedpush -o jsonpath='{.status.pushApplicationId}'
----

Here are all of the configurable fields in an IOSVariant:

|===
|Field Name |Description

|pushApplicationId
|ID of the PushApplication that this variant corresponds to

|description
|Human friendly description for the variant

|certificate
|The base64 encoded APNs certificate that is needed to establish a
 connection to Apple's APNs Push Servers

|passphrase
|The APNs passphrase that is needed to establish a connection to
 Apple's APNs Push Servers

|production
|If `true`, indicates that a connection to production APNs server should
 be used. If `false` a connection to the Sandbox/Development APNs server
 will be used.
|===

* Apply an AndroidVariantCR based on the example a link:./deploy/crds/examples/push_v1alpha1_iosvariant_cr.yaml[IOSVariant CR]  as follows:
+
[source,shell]
----
kubectl apply -n unifiedpush -f ./deploy/crds/push_v1alpha1_iosvariant_cr.yaml
----

=== Uninstalling

Use the following command to delete all related configuration applied by the `make install` of this project.

[source,shell]
----
$ make cluster/clean
----

NOTE: To uninstall you need be logged in as a user with cluster privileges like the `system:admin` user. E.g. By using: `oc login -u system:admin`.

== Configuration

=== UnifiedPushServer

This is the main installation resource kind. Creation of a valid
UnifiedPushServer CR will result in a functional AeroGear
UnifiedPushServer deployed to your namespace.

[NOTE]
====
This operator currently only supports one UnifiedPushServer CR to be
created.
====

Here are all of the configurable fields in a UnifiedPushServer:

.UnifiedPushServer fields
|===
|Field Name |Description

|backups
|A list of backup entries that CronJobs will be created from. See
 `./deploy/crds/push_v1alpha1_unifiedpushserver_cr_with_backup.yaml`
 for an annotated example. Note that a ServiceAccount called
 "backupjob" must already exist before the operator will create any
 backup CronJobs. See
 https://github.com/integr8ly/backup-container-image/tree/master/templates/openshift/rbac
 for an example.
|===

The most basic UnifiedPushServer CR doesn't specify anything in the
Spec section, so the example in
`./deploy/crds/push_v1alpha1_unifiedpushserver_cr.yaml` is a good
template:

.push_v1alpha1_unifiedpushserver_cr.yaml
[source,yaml]
----
apiVersion: push.aerogear.org/v1alpha1
kind: UnifiedPushServer
metadata:
  name: example-unifiedpushserver
----

To create this, you can run:

....
kubectl apply -n unifiedpush -f ./deploy/crds/push_v1alpha1_unifiedpushserver_cr.yaml
....

To see the created instance then, you can run:

....
kubectl get ups example-unifiedpushserver -n unifiedpush -o yaml
....

=== Image Streams

The operator uses 3 image streams and what image streams to use are configurable
with environment variables.

Unified Push Server and Oauth proxy image stream are created within the same namespace by the operator.
However, for Postgres the image stream in `openshift` namespace is used.

The following table shows the available
environment variable names, along with their default values:

.Environment Variables
|===
|Name |Default |Purpose

|`UPS_IMAGE_STREAM_NAME`
|`ups-imagestream`
| Name of the Unified Push image stream that will be created by the operator.

|`UPS_IMAGE_STREAM_TAG`
|`latest`
| Tag of the Unified Push image stream that will be created by the operator.

|`UPS_IMAGE_STREAM_INITIAL_IMAGE`
|`docker.io/aerogear/unifiedpush-wildfly-plain:2.2.1.Final`
| Initial image for the Unified Push image stream that will be created by the operator.

|`OAUTH_PROXY_IMAGE_STREAM_NAME`
|`ups-oauth-proxy-imagestream`
| Name of the Oauth proxy image stream that will be created by the operator.

|`OAUTH_PROXY_IMAGE_STREAM_TAG`
|`latest`
| Tag of the Oauth proxy image stream that will be created by the operator.

|`OAUTH_PROXY_IMAGE_STREAM_INITIAL_IMAGE`
|`docker.io/openshift/oauth-proxy:v1.1.0`
| Initial image for the Oauth proxy image stream that will be created by the operator.

|`POSTGRES_IMAGE_STREAM_NAMESPACE`
|`openshift`
| Namespace to look for the Postgres image stream.

|`POSTGRES_IMAGE_STREAM_NAME`
|`postgresql`
| Name of the Postgres image stream to look for.

|`OAUTH_PROXY_IMAGE_STREAM_TAG`
|`10`
| Tag of the Postgres image stream.

|===

CAUTION: Re-deploying this operator with customized images will cause
_all_ instances owned by the operator to be updated.

=== Container Names

If you would like to modify the container names, you can use the following environment variables.

.Environment Variables
|===
|Name |Default

|`UPS_CONTAINER_NAME`
|`ups`

|`OAUTH_PROXY_CONTAINER_NAME`
|`ups-oauth-proxy`

|`POSTGRES_CONTAINER_NAME`
|`postgresql`

|===

=== Backups

The `BACKUP_IMAGE` environment variable configures what image to use for backing up
the custom resources created by this operator. Default value is `quay.io/integreatly/backup-container:1.0.8`.

=== Monitoring Service (Metrics)

The application-monitoring stack provisioned by the
{application_monitoring_operator} on https://github.com/integr8ly[Integr8ly]
can be used to gather metrics from this operator and the UnifiedPush Server. These metrics can be used by Integr8ly's application monitoring to generate Prometheus metrics, AlertManager alerts and a Grafana dashboard.

It is required that the https://github.com/integr8ly/grafana-operator[integr8ly/Grafana] and https://github.com/coreos/prometheus-operator[Prometheus] operators are installed. For further detail see https://github.com/integr8ly/application-monitoring-operator[integr8ly/application-monitoring-operator].

The following command enables the monitoring service in the operator namespace:

[source,shell]
----
make monitoring/install
----

IMPORTANT: The namespaces are setup manually in the files link:./deploy/monitor/service_monitor.yaml[ServiceMonitor], link:./deploy/monitor/prometheus_rule.yaml[Prometheus Rules], link:./deploy/monitor/operator-service.yaml[Operator Service], and link:./deploy/monitor/grafana-dashboard[Grafana Dashboard]. Following an example from the link:./deploy/monitor/prometheus_rule.yaml[Prometheus Rules]. You should replace them if the operator is not installed in the default namespace.

[source,yaml]
----
  expr: |
          (1-absent(kube_pod_status_ready{condition="true", namespace="mobile-security-service"})) or sum(kube_pod_status_ready{condition="true", namespace="mobile-security-service"}) != 3

[source,shell]
----

NOTE: The command `make monitoring/uninstall` will uninstall the Monitor Service.

== Development

=== Running the operator

1. Prepare the operator project:

....
make cluster/prepare
....

2. Run the operator (locally, not in OpenShift):

....
make code/run
....

3. Create a UPS instance (in another terminal):

....
kubectl apply -f deploy/crds/push_v1alpha1_unifiedpushserver_cr.yaml -n unifiedpush
....

4. Watch the status of your UPS instance provisioning (optional):

....
watch -n1 "kubectl get po -n unifiedpush && echo '' && kubectl get ups -o yaml -n unifiedpush"
....

5. If you want to be able to work with resources that require the
local instance of your operator to be able to talk to the UPS instance
in the cluster, then you'll need to make a corresponding domain name
available locally. Something like the following should work, by adding
an entry to /etc/hosts for the example Service that's created, then
forwarding the port from the relevant Pod in the cluster to the local
machine. Run this in a separate terminal, and ctrl+c to clean it up
when finished:

// TODO: We could maybe use a non-privileged port instead of :80?
....
# su/sudo is needed to be able to:
# - modify /etc/hosts
# - bind to port :80
KUBECONFIG=$HOME/.kube/config su -c "echo '127.0.0.1   example-unifiedpushserver-unifiedpush' >> /etc/hosts && kubectl port-forward $(kubectl get po -l service=ups -o name) 80:8080 && sed -i -e 's/^127.0.0.1   example-unifiedpushserver-unifiedpush$//g' -e '/^[[:space:]]*$/d' /etc/hosts"
....

6. When finished, clean up:

....
make cluster/clean
....

== Testing

=== Run unit tests

....
make test/unit
....

=== Run e2e tests

. Export env vars used in commands below

....
export NAMESPACE="<name-of-your-openshift-project-used-for-testing>"
export IMAGE="quay.io/<your-account-name>/unifiedpush-operator"
....

. Login to OpenShift cluster as a user with cluster-admin role

....
oc login <url> --token <token>
....

. Prepare a new OpenShift project for testing

....
make NAMESPACE=$NAMESPACE cluster/prepare
....

. Modify the operator image name in manifest file

....
yq w -i deploy/operator.yaml spec.template.spec.containers[0].image $IMAGE
....

Note: If you do not have link:https://mikefarah.github.io/yq/[yq] installed, just simply edit the image name in link:deploy/operator.yaml[deploy/operator.yaml]

. Build & push the operator container image to your Dockerhub/Quay image repository, e.g.

....
operator-sdk build $IMAGE --enable-tests && docker push $IMAGE
....

. Run the test

....
operator-sdk test cluster $IMAGE --namespace $NAMESPACE --service-account unifiedpush-operator
....

== Publishing images

Images are automatically built and pushed to our https://quay.io/repository/aerogear/unifiedpush-operator[image repository] by the Jenkins in the following cases:

- For every change merged to master a new image with the `master` tag is published.
- For every change merged that has a git tag a new image with the `<operator-version>` and `latest` tags are published.

== Tags Release

Following the steps

. Create a new version tag following the http://semver.org/spec/v2.0.0.html[semver], for example `0.1.0`
. Bump the version in the link:./version/version.go[version.go] file.
. Update the the link:./CHANGELOG.MD[CHANGELOG.MD] with the new release.
. Update any tag references in all SOP files (e.g `https://github.com/aerogear/unifiedpush-operator/blob/0.1.0/SOP/SOP-operator.adoc`)
. Create a git tag with the version value, for example:
+
[source,shell]
----
$ git tag -a 0.1.0 -m "version 0.1.0"
----
+
. Push the new tag to the upstream repository, this will trigger an automated release by the Jenkins, for example:
+
[source,shell]
----
$ git push upstream 0.1.0
----
+
NOTE: The image with the tag will be created and pushed to the https://quay.io/repository/aerogear/unifiedpush-operator[unifiedpush-operator image hosting repository] by the Jenkins.

== Architecture

This operator is `cluster-scoped`. For further information see the https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#operator-scope[Operator Scope] section in the Operator Framework documentation. Also, check its roles in link:./deploy/[Deploy] directory.

NOTE: The operator, application and database will be installed in the namespace which will be created by this project.

=== CI/CD

==== CircleCI

* Coveralls
* Unit Tests

NOTE: See the link:./circleci/config.yml[config.yml].

==== Jenkins

* Integration Tests
* Build of images

NOTE: See the link:./Jenkinsfile[Jenkinsfile].

== Makefile command reference

=== Application

|===
| *Command*                        | *Description*
| `make install`                   | Creates the `{namespace}` namespace, application CRDS, cluster role and service account.
| `make cluster/clean`                  | It will delete what was performed in the `make cluster/prepare` .
| `make monitoring/install`        | Installs Monitoring Service in order to provide metrics
| `make monitoring/uninstall`      | Uninstalls Monitoring Service in order to provide metrics, i.e. all configuration applied by `make monitoring/install`
| `make example-pushapplication/apply`  | Applies the Example PushApplication CR `
| `make example-pushapplication/delete`  | Delete the Example PushApplication CR `
| `make cluster/prepare`                | It will apply all less the operator.yaml.
|===


=== Local Development

|===
| `make code/run`                       | Runs the operator locally for development purposes.
| `make code/gen`                       | Sets up environment for debugging proposes.
| `make code/vet`                       | Examines source code and reports suspicious constructs using https://golang.org/cmd/vet/[vet].
| `make code/fix`                       | Formats code using https://golang.org/cmd/gofmt/[gofmt].
|===

=== Jenkins

|===
| `make test/compile`                      | Compile image to be used in the e2e tests
| `make code/compile`                      | Compile image to be used by Jenkins
|===

===  Tests / CI

|===
| `make test/integration-cover`          | It will run the coveralls.
| `make test/unit`                       | Runs unit tests
| `make code/build/linux`                | Build image with the parameters required for CircleCI
|===

NOTE: The link:./Makefile[Makefile] is implemented with tasks which you should use to work with.

== Supportability

This operator was developed using the Kubernetes and Openshift APIs.

Currently this project requires the usage of the https://docs.openshift.com/container-platform/3.11/rest_api/apis-route.openshift.io/v1.Route.html[v1.Route] to expose the service and https://github.com/openshift/oauth-proxy[OAuth-proxy] for authentication which make it unsupportable for Kubernetes.
Also, it is using https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/builds_and_image_streams.html[ImageStream] which is from the OpenShift API specifically. In this way, this project is not compatible with Kubernetes, however, in future we aim to make it work on vanilla Kubernetes also.

== Security Response

If you've found a security issue that you'd like to disclose confidentially please contact the {rh_product_security}.

== Legal

The UnifiedPush Operator is licensed under the {apache_license}
License, and is subject to the {export_policy}.

== Contributing

All contributions are hugely appreciated. Please see our https://aerogear.org/community/#guides[Contributing Guide] for guidelines on how to open issues and pull requests. Please check out our link:./.github/CODE_OF_CONDUCT.md[Code of Conduct] too.

== Questions

There are a number of ways you can get in in touch with us, please see the https://aerogear.org/community/#contact[AeroGear community].