apiVersion: push.aerogear.org/v1alpha1
kind: UnifiedPushServer
metadata:
  name: example-unifiedpushserver
spec:
  unifiedPushResourceRequirements:
    limits:
      memory: "3Gi"
      cpu: "2"
    requests:
      memory: "1Gi"
      cpu: "1"
  oAuthResourceRequirements:
    limits:
      memory: "128Mi"
      cpu: "100m"
    requests:
      memory: "64Mi"
      cpu: "50m"
  postgresResourceRequirements:
    limits:
      memory: "2Gi"
      cpu: "2"
    requests:
      memory: "1Gi"
      cpu: "1"
  postgresPVCSize: "10Gi"
