apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iosvariants.push.aerogear.org
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.production
    name: Production
    type: boolean
  - JSONPath: .status.variantId
    name: VariantId
    type: string
  - JSONPath: .status.ready
    name: Ready
    type: string
  group: push.aerogear.org
  names:
    kind: IOSVariant
    listKind: IOSVariantList
    plural: iosvariants
    singular: iosvariant
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            certificate:
              description: Certificate defines the base64 encoded APNs certificate
                that is needed to establish a connection to Apple's APNs Push Servers.
              type: string
            description:
              description: Description is human friendly description for the variant.
              type: string
            passphrase:
              description: Passphrase defines the APNs passphrase that is needed to
                establish a connection to any of Apple's APNs Push Servers.
              type: string
            production:
              description: Production defines if a connection to production APNS server
                should be used. If false, a connection to Apple's Sandbox/Development
                APNs server will be established for this iOS variant.
              type: boolean
          required:
          - certificate
          - passphrase
          - production
          type: object
        status:
          properties:
            ready:
              type: boolean
            variantId:
              type: string
          required:
          - ready
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
