apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: unifiedpushservers.push.aerogear.org
spec:
  group: push.aerogear.org
  names:
    kind: UnifiedPushServer
    listKind: UnifiedPushServerList
    plural: unifiedpushservers
    shortNames:
    - ups
    singular: unifiedpushserver
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            backups:
              description: Backups is an array of configs that will be used to create
                CronJob resource instances
              items:
                properties:
                  backendSecretName:
                    description: BackendSecretName is the name of a secret containing
                      storage backend details, such as "AWS_S3_BUCKET_NAME", "AWS_ACCESS_KEY_ID",
                      and "AWS_SECRET_ACCESS_KEY"
                    type: string
                  backendSecretNamespace:
                    description: BackendSecretNamespace is the name of the namespace
                      that the secret referenced in BackendSecretName resides in
                    type: string
                  encryptionKeySecretName:
                    description: EncryptionKeySecretName is the name of a secret containing
                      PGP/GPG details, including "GPG_PUBLIC_KEY", "GPG_TRUST_MODEL",
                      and "GPG_RECIPIENT"
                    type: string
                  encryptionKeySecretNamespace:
                    description: EncryptionKeySecretNamespace is the name of the namespace
                      that the secret referenced in EncryptionKeySecretName resides
                      in
                    type: string
                  name:
                    description: Name is the name that will be given to the resulting
                      CronJob
                    type: string
                  schedule:
                    description: Schedule is the schedule that the job will be run
                      at, in cron format
                    type: string
                required:
                - name
                - schedule
                - backendSecretName
                type: object
              type: array
            oAuthCpuLimit:
              description: Limit of CPU which will be available for the OAuth container
              type: string
            oAuthCpuRequest:
              description: CPU resource which will be available for the OAuth container
              type: string
            oAuthMemoryLimit:
              description: Limit of Memory which will be available for the OAuth container
              type: string
            oAuthMemoryRequest:
              description: Limit of Memory Request which will be available for the
                OAuth container
              type: string
            postgresCpuLimit:
              description: Limit of CPU which will be available for the Postgres container
              type: string
            postgresCpuRequest:
              description: CPU resource which will be available for the Postgres container
              type: string
            postgresMemoryLimit:
              description: Limit of Memory which will be available for the Postgres
                container
              type: string
            postgresMemoryRequest:
              description: Limit of Memory Request which will be available for the
                Postgres container
              type: string
            postgresPVCSize:
              description: PVC size for Postgres service
              type: string
            unifiedPushCpuLimit:
              description: Limit of CPU which will be available for the UnifiedPush
                Service container
              type: string
            unifiedPushCpuRequest:
              description: CPU resource which will be available for the UnifiedPush
                Service container
              type: string
            unifiedPushMemoryLimit:
              description: Limit of Memory which will be available for the UnifiedPush
                Service container
              type: string
            unifiedPushMemoryRequest:
              description: Limit of Memory Request which will be available for the
                UnifiedPush Service container
              type: string
            useMessageBroker:
              description: UseMessageBroker can be set to true to use managed queues,
                if you are using enmasse. Defaults to false.
              type: boolean
          type: object
        status:
          properties:
            phase:
              type: string
          required:
          - phase
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
