{
 "title": "UnifiedPush Operator",
 "description": "Operator metrics",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "up{job='unifiedpush-operator'}", "legendFormat": "{{service}} - Uptime" }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job='unifiedpush-operator'}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{job='unifiedpush-operator'}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job='unifiedpush-operator'}[1m]))*1000",
     "legendFormat": "UnifiedPush Operator- CPU Usage in Millicores"
    }
   ]
  }
 ]
}