{
 "title": "UnifiedPush Server",
 "description": "Application metrics",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Admin Console - Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_endpoint_address_available{endpoint='example-unifiedpushserver-unifiedpush'}",
     "legendFormat": "uptime service endpoint"
    }
   ]
  },
  {
   "title": "UnifiedPush Database - Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 3, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_pod_container_status_running{namespace='unifiedpush',container='postgresql'})",
     "legendFormat": "database container "
    }
   ]
  },
  {
   "title": "UnifiedPush Server  - Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 3, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kube_pod_container_status_running{namespace='unifiedpush',container='ups'})",
     "legendFormat": "server container"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Current Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(jvm_memory_bytes_used{area='heap',namespace='unifiedpush'}) + max(jvm_memory_bytes_used{area='nonheap', namespace='unifiedpush'})",
     "legendFormat": "JVM memory"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{namespace=\"unifiedpush\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{namespace=\"unifiedpush\"})",
     "legendFormat": "commited"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{namespace=\"unifiedpush\"})",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_cpu_seconds_total{namespace=\"unifiedpush\"})",
     "legendFormat": "used"
    }
   ]
  },
  { "title": "API Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Push Notifications",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aerogear_ups_push_requests_total{namespace='unifiedpush',service='example-unifiedpushserver-unifiedpush'})",
     "legendFormat": "attempts"
    },
    {
     "expr": "sum(aerogear_ups_push_requests_fail_total{namespace='unifiedpush',service='example-unifiedpushserver-unifiedpush'})",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "Push Notifications per Platform",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aerogear_ups_push_requests_ios{namespace='unifiedpush',service='example-unifiedpushserver-unifiedpush'})",
     "legendFormat": "ios"
    },
    {
     "expr": "sum(aerogear_ups_push_requests_android{namespace='unifiedpush',service='example-unifiedpushserver-unifiedpush'})",
     "legendFormat": "android"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aerogear_ups_device_register_requests_total{namespace='unifiedpush',service='example-unifiedpushserver-unifiedpush'}",
     "legendFormat": "requests to register devices"
    }
   ]
  }
 ]
}