// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiedPushServer) DeepCopyInto(out *UnifiedPushServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiedPushServer.
func (in *UnifiedPushServer) DeepCopy() *UnifiedPushServer {
	if in == nil {
		return nil
	}
	out := new(UnifiedPushServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiedPushServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiedPushServerList) DeepCopyInto(out *UnifiedPushServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UnifiedPushServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiedPushServerList.
func (in *UnifiedPushServerList) DeepCopy() *UnifiedPushServerList {
	if in == nil {
		return nil
	}
	out := new(UnifiedPushServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiedPushServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiedPushServerSpec) DeepCopyInto(out *UnifiedPushServerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiedPushServerSpec.
func (in *UnifiedPushServerSpec) DeepCopy() *UnifiedPushServerSpec {
	if in == nil {
		return nil
	}
	out := new(UnifiedPushServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiedPushServerStatus) DeepCopyInto(out *UnifiedPushServerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiedPushServerStatus.
func (in *UnifiedPushServerStatus) DeepCopy() *UnifiedPushServerStatus {
	if in == nil {
		return nil
	}
	out := new(UnifiedPushServerStatus)
	in.DeepCopyInto(out)
	return out
}
