ifdef::env-github[]
:status:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:table-caption!:
endif::[]

:toc:
:toc-placement!:

= UnifiedPush Operator - Standard Operating Procedures

:toc:
toc::[]

== Overview

The following guide outlines the steps required to manage and solve issues in the https://github.com/aerogear/unifiedpush-operator[UnifiedPush Operator].

== Reference Articles

- https://github.com/aerogear/unifiedpush-operator[UnifiedPush Operator]
- https://prometheus.io/docs/practices/alerting/[Prometheus Alerts documentation]
- https://github.com/operator-framework[operator-framework]

== Success Indicators

All alerts should appear as green in the Prometheus Alert Monitoring.

== Prometheus Alerts Procedures

The following guide outlines the steps required to resolve issues with the Prometheus alerts configured to monitor the https://github.com/aerogear/unifiedpush-operator[UnifiedPush Operator]. The alerts are configured by enabling the https://github.com/aerogear/unifiedpush-operator#monitoring-service-metrics[Monitoring Service (Metrics)] for this project.

== Critical

=== UnifiedPushOperatorDown

. Switch to the UnifiedPush namespace by running `oc project <namespace>`. E.g `oc project unifiedpush`.
. Follow the <<Validate>> steps.
+
NOTE: The operator is responsible to manage and create all objects required in order to have the UnifiedPush Service and its database provided in the cluster.
. Check its logs by running `oc logs <operator-podname>`
+
NOTE: You can save the logs by running `oc logs <operator-podname> > <filename>.log`. The logs may provide you with useful information to lead you to the root cause, and they are also useful for providing to the project maintainers when you create an issue.

== Validate

. Switch to the UnifiedPush namespace by running `oc project <namespace>`. E.g `oc project unifiedpush`.
. Check if the operator pod to is present by running `oc get pods | grep operator`. Following an example of the expected result.
+
[source,shell]
----
$ oc get pods | grep operator
unifiedpush-operator-58c8877fd8-g6dvr          1/1       Running   3          9d
----

== Monitoring

If the https://github.com/aerogear/unifiedpush-operator#monitoring-service-metrics[Monitoring Service (Metrics)] is enabled for the installation, a Grafana Dashboard titled `UnifiedPush Operator`, and the Prometheus Monitoring instance are created.

== AMQ Integration

There is a variable that is responsable for switching AMQ usage in the unifiedpushserver custom resource:

```yaml
apiVersion: push.aerogear.org/v1alpha1
kind: UnifiedPushServer
metadata:
  name: unifiedpush
spec:
  useMessageBroker: false #set this value to true and update the cr
```

This will trigger the creation of some AMQ resources: `address`, `addressspace` and `messagingusers`.

Sometimes AMQ adresses might get stuck in a `pending` state:

```
$ oc get address -n mobile-unifiedpush
NAME                                      ADDRESS                               READY     PHASE     AGE
ups.allbatchesloadedqueue                 AllBatchesLoadedQueue                 true      Active    25m
ups.apnspushmessagequeue                  APNsPushMessageQueue                  false     Pending   25m
ups.apnstokenbatchqueue                   APNsTokenBatchQueue                   false     Pending   25m
ups.batchloadedqueue                      BatchLoadedQueue                      true      Active    25m
ups.freeserviceslotqueue                  FreeServiceSlotQueue                  true      Active    25m
ups.gcmpushmessagequeue                   GCMPushMessageQueue                   true      Active    25m
ups.gcmtokenbatchqueue                    GCMTokenBatchQueue                    true      Active    25m
ups.metricsqueue                          MetricsQueue                          true      Active    25m
ups.triggermetriccollectionqueue          TriggerMetricCollectionQueue          true      Active    25m
ups.triggervariantmetriccollectionqueue   TriggerVariantMetricCollectionQueue   true      Active    25m
ups.wnspushmessagequeue                   WNSPushMessageQueue                   true      Active    25m
ups.wnstokenbatchqueue                    WNSTokenBatchQueue                    true      Active    25m
```

UPS needs to be rolled out again once all adresses are ready:

```
oc rollout latest unifiedpush -n openshift-mobile-unifiedpush
```

The rollout status can be verified/watched by running the following command:

```
oc rollout status dc/unifiedpush -n openshift-mobile-unifiedpush
```

If an address gets stuck for some time, it should be deleted by running `oc delete address/$name -n mobile-unifiedpush` to trigger an adress recreation by the operator.

NOTE: This process won't migrate messages from the internal UPS system to AMQ and results in a tiny UPS downtime (if no unexpected issues show up such as image pulling issues).
