ifdef::env-github[]
:status:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:table-caption!:
endif::[]

:toc:
:toc-placement!:

= UnifiedPush Operator - Standard Operating Procedures

:toc:
toc::[]

== Overview

The following guide outlines the steps required to manage and solve issues in the https://github.com/aerogear/unifiedpush-operator[UnifiedPush Operator].

== Reference Articles

- https://github.com/aerogear/unifiedpush-operator[UnifiedPush Operator]
- https://prometheus.io/docs/practices/alerting/[Prometheus Alerts documentation]
- https://github.com/operator-framework[operator-framework]

== Success Indicators

All alerts should appear as green in the Prometheus Alert Monitoring.

== Prometheus Alerts Procedures

The following guide outlines the steps required to resolve issues with the Prometheus alerts configured to monitor the https://github.com/aerogear/unifiedpush-operator[UnifiedPush Operator]. The alerts are configured by enabling the https://github.com/aerogear/unifiedpush-operator#monitoring-service-metrics[Monitoring Service (Metrics)] for this project.

== Critical

=== UnifiedPushOperatorDown

. Switch to the UnifiedPush namespace by running `oc project <namespace>`. E.g `oc project unifiedpush`.
. Follow the <<Validate>> steps.
+
NOTE: The operator is responsible to manage and create all objects required in order to have the UnifiedPush Service and its database provided in the cluster.
. Check its logs by running `oc logs <operator-podname>`
+
NOTE: You can save the logs by running `oc logs <operator-podname> > <filename>.log`. The logs may provide you with useful information to lead you to the root cause, and they are also useful for providing to the project maintainers when you create an issue.

== Validate

. Check if the operator pod to is present by running `oc get pods | grep operator`. Following an example of the expected result.
+
[source,shell]
----
$ oc get pods | grep operator
unifiedpush-operator-58c8877fd8-g6dvr          1/1       Running   3          9d
----

== Monitoring

If the https://github.com/aerogear/unifiedpush-operator#monitoring-service-metrics[Monitoring Service (Metrics)] is enabled for your installation you are able to check its Grafana Dashboard, `UnifiedPush Operator`, and the Prometheus Monitoring instance used for it.
